node50,cli-eu-central-1
node51,cli-eu-central-2
node52,cli-eu-north-1
node53,cli-eu-south-1
node54,cli-eu-south-2
node55,cli-eu-west-1
node56,cli-eu-west-2
node57,cli-eu-west-3
node58,cli-mx-central-1
node59,cli-us-east-1
node60,cli-us-east-2
node61,cli-us-west-1
node62,cli-us-west-2
node63,cli-ca-central-1
node64,cli-ca-west-1
