node65,cli-ca-central-1
node66,cli-ca-west-1
node67,cli-eu-central-1
node68,cli-eu-central-2
node69,cli-eu-north-1
node70,cli-eu-south-1
node71,cli-eu-south-2
node72,cli-eu-west-1
node73,cli-eu-west-2
node74,cli-eu-west-3
node75,cli-mx-central-1
node76,cli-us-east-1
node77,cli-us-east-2
node78,cli-us-west-1
node79,cli-us-west-2
